/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings` (hash: 4e2aa2d0a51ecd51ad08852e442ee5fd)
// Runtime types generated with workerd@1.20260317.1 2025-12-17 nodejs_compat
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
    durableNamespaces: 'InteractionAnalyzerContainer';
  }
  interface Env {
    ENVIRONMENT: 'prod' | 'dev' | 'local';
    AXIOM_DATASET: 'crow-traces';
    AUTH_SERVICE_URL: 'https://dev.internal.auth-api.crowai.dev';
    PRODUCT_SERVICE_URL:
      | 'https://dev.internal.products.crowai.dev'
      | 'http://localhost:8006';
    WEB_INGEST_SERVICE_URL:
      | 'https://dev.internal.ingest-worker.crowai.dev'
      | 'http://localhost:8013';
    CLOUDFLARE_D1_ACCOUNT_ID: string;
    CLOUDFLARE_D1_API_TOKEN: string;
    CLOUDFLARE_D1_DATABASE_ID: string;
    S3_API: string;
    R2_ACCESS_KEY_ID: string;
    R2_SECRET_ACCESS_KEY: string;
    AXIOM_API_TOKEN: string;
    INTERACTION_ANALYZER: DurableObjectNamespace<
      import('./src/index').InteractionAnalyzerContainer
    >;
    R2_BUCKET: R2Bucket;
    DB: D1Database;
    INTERACTION_QUEUE: Queue;
    CCTV_QUEUE: Queue;
    AI: Ai;
  }
}
interface CloudflareBindings extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Cloudflare.Env> {}
}
